CBF fixes

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-declare TOP
-
 #----------------------------------------------------------------------------------------------
 function my.usage()
 {
@@ -9,19 +7,27 @@ function my.usage()
 
     cat >&2 << EOF
 Usage:
-    $progname [ -h|--help ] | [ --clean ] | [ --init ] [ --latest ]
+    $progname [ -h|--help ]
+              | [ --clean ]
+              | [ --init ]
+              | [ --latest ]
+              | [ --promote <branch> ]
 
     Common options:
         -h --help              Display a basic set of usage instructions
         -c --clean             0:do not clean environment
                                1:clean environment before build (default)
+        -d --down              stop services defined by 'docker-compose.yml'
         -i --init              only initialize the environment
-        -l --latest            update to latest versions of jars rather than using those defined in docker-compose.yml
+        -l --latest            update to latest versions of images rather than using those defined in docker-compose.yml
+        -p --promote <branch>  promote images in docker repo, from current <branch> to target <branch>
+                               this retags the image with the target <branch>, 
+                                   on protected branches {eg: master or integration } the ':latest' tag is used
+                               after a pull request has completed the new images should be pushed to the registry.
 
 EOF
     exit "$exit_status"
 }
-export -f my.usage
 
 #----------------------------------------------------------------------------------------------
 function my.cmdLineArgs()
@@ -32,7 +38,7 @@ function my.cmdLineArgs()
 
     # Parse command-line options into above variable
     local -r progname="$( basename "${BASH_SOURCE[0]}" )"
-    local -r options=$(getopt --longoptions "help,Help,HELP,clean,init,latest" --options "Hhcil" --name "$progname" -- "$@") || "$usage" $?
+    local -r options=$(getopt --longoptions "help,Help,HELP,clean,down,init,latest,promote:" --options "Hhcdilp:" --name "$progname" -- "$@") || "$usage" $?
     eval set -- "$options"
 
     local -A opts=()
@@ -43,49 +49,16 @@ function my.cmdLineArgs()
             -H|--H|--HELP|-HELP)  "$usage" 1;;
             --Help|-Help)         "$usage" 1;;
             -c|--c|--clean)       opts['clean']=1; shift;;
+            -d|--d|--down)        opts['down']=1; shift;;
             -i|--i|--init)        opts['init']=1; shift;;
             -l|--l|--latest)      opts['latest']=1; shift;;
+            -p|--p|--promote)     opts['promote']=$2; shift 2;;
             --)                   shift; break;;
         esac
     done
     
-    local val
-    if [ ${#opts[*]} -gt 0 ]; then
-        local -i i=0
-        for val in "${!opts[@]}"; do
-            [ $(( i++ )) -gt 0 ] && echo -n ' '
-            printf '['\''%s'\'']='\''%s'\' "$val" "${opts[$val]}"
-        done
-    fi
-    echo
-    if [ $# -gt 0 ]; then
-        for val in "$@"; do
-            echo "$val"
-        done
-    fi
+    appenv.results "$@"
 }
-export -f my.cmdLineArgs
-
-#----------------------------------------------------------------------------------------------
-function my.loadLibs()
-{
-    local fn="${1:?}"
-
-    if [ "$(env | grep -c "BASH_FUNC_${fn}%%")" -eq 0 ]; then
-        top="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
-        if [ "$top" = '/usr/local/bin' ] && [ -e /usr/local/crf/bin/loadLibraries.sh ]; then       
-            source /usr/local/crf/bin/loadLibraries.sh
-            TOP=/opt
-        elif [ -e "${top}/libs/loadLibraries.sh" ]; then
-            source "${top}/libs/loadLibraries.sh"
-            TOP="$top"
-            environ.container
-        else
-            echo '***ERROR unable to locate libraries'; exit 1
-        fi
-    fi
-}
-export -f my.loadLibs
 
 #----------------------------------------------------------------------------------------------
 
@@ -93,7 +66,13 @@ declare -i status
 declare -a args
 declare fn=deploy.main
 
-my.loadLibs "$fn"
-: ${BASE_TAG:=latest}
+declare loader="$(dirname "${BASH_SOURCE[0]}")/libs/appenv.bashlib"
+if [ ! -e "$loader" ]; then
+    echo 'Unable to load libraries'
+    exit 1
+fi
+source "$loader"
+appenv.loader "$fn"
+
 args=( $( my.cmdLineArgs "$TOP" "$@" ) ) && status=$? || status=$?
 [ $status -eq 0 ] && "$fn" "${args[@]}" 
